FROM python:3.10

RUN mkdir -p /Users/litann/Desktop/OOP4/bot
WORKDIR /Users/litann/Desktop/OOP4/bot

COPY . /Users/litann/Desktop/OOP4/bot
RUN pip3 install -r requirements.txt

CMD ["python3", "bot.py"]